# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_feed_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='likes',
        ),
    ]
