# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_feed_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
