# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20170614_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userkey',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='userkey',
            new_name='user',
        ),
    ]
