# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20170628_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='key',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
